# Not Implemented
FROM docker.io/library/mariadb
WORKDIR /

RUN apt update -y && apt install -y mysql-client
RUN rmdir /home /mnt /media /srv

COPY guacamole_db_setup_files/001-create-schema.sql /docker-entrypoint-initdb.d/
COPY guacamole_db_setup_files/002-create-admin-user.sql /docker-entrypoint-initdb.d/
COPY guacamole_db_setup_files/003-grant-all.sql /docker-entrypoint-initdb.d/
