FROM mariadb:latest
WORKDIR /

RUN apt update -y && apt install net-tools
RUN rmdir /home /mnt /media /srv
RUN mkdir /opt/scripts
# Setup the OS like I want and organize the build process
COPY guacamole_db_setup_files/001-create-schema.sql /opt/scripts
COPY guacamole_db_setup_files/002-create-admin-user.sql /opt/scripts
COPY scripts/import_guacdb.bash /opt/scripts/
RUN bash /opt/scripts/import_guacdb.bash 
EXPOSE 3306
