# Must be placed in /etc/guacamole (cant find a place to override this behavior unless maybe it's in the compile flags..?
#For now, we'll just link the /app/guacamole/guacd.conf to /etc/guacamole/guacd.conf

[daemon]
pid_file = /var/run/guacd.pid
log_level = debug

[server]
#bind_host = localhost
bind_host = 127.0.0.1
bind_port = 4822

#[ssl]
#server_certificate = /etc/ssl/certs/guacd.crt
#server_key = /etc/ssl/private/guacd.key
