guacd-hostname: 127.0.0.1
guacd-port:     4822
#user-mapping:   /app/guacamole-client/user-mapping.xml


#auth-provider:  net.sourceforge.guacamole.net.basic.BasicFileAuthenticationProvider
mysql-hostname: 127.0.0.1
mysql-port: 3306
mysql-database: guac
mysql-username: guac
mysql-password: guac


# Auth provider class
auth-provider: net.sourceforge.guacamole.net.auth.ldap.LDAPAuthenticationProvider
# LDAP properties
ldap-hostname:           192.168.1.200
ldap-port:               389
ldap-user-base-dn:       cn=users,cn=accounts,dc=lab,dc=sanderson,dc=com
ldap-username-attribute: uid
ldap-config-base-dn:     cn=groups,cn=accounts,dc=lab,dc=sanderson,dc=com

# When the guacamole-auth-sso-openid-1.6.0.jar extenion file is loaded then the Guacamole Login page will fail to load and show an error.
openid-authorization-endpoint: https://lcaolhost.blah
openid-client-id: b5b4ceff-9b04-44b6-ad38-149a59b94c9a
openid-redirect-uri: https://localhost.blah

# Needed for SSL extension to start and not give login  page error
ssl-auth-primary-uri: https://guac.lab.sanderson.com:8443
ssl-auth-uri: https://guac.lab.sanderson.com:8443

# Section for HTTP HEADER authentication
auth-provider: net.sourceforge.guacamole.netauth.HTTPHeaderAuthenticationProvider

# Header to look for
http-auth-header: Remote-User

# (Optional) Map cert user to Guacamole user if needed
#http-header-mapping: /etc/guacamole/header-mapping.json
