[ req ]
default_bits = 2048
prompt = no
default_md = sha256
req_extensions = req_ext
distinguished_name = dn

[ dn ]
C = US
ST = AL
L = Huntsville
O = LAB
OU = IT
CN = *.lab.sanderson.com

[ req_ext ]
subjectAltName = @alt_names

[ alt_names ]
DNS.1 = lab.sanderson.com
DNS.1 = guac.lab.sanderson.com
IP.1 = 192.168.1.44
