server {
  listen 443 ssl default_server;
  server_name *.lab.sanderson.com;
  #ssl_protocols SSLv3 TLSv1;
  #ssl_ciphers ALL:!aNULL:!ADH:!eNULL:!LOW:!EXP:RC4+RSA:+HIGH:+MEDIUM;
  access_log /var/log/nginx/access.log;
  error_log  /var/log/nginx/error.log info;
  ssl_certificate /etc/nginx/ssl/guac.lab.sanderson.com.crt;
  ssl_certificate_key /etc/nginx/ssl/guac.lab.sanderson.com.key;
  ignore_invalid_headers off;

# Smart Card/Client Certificate Authentication
	ssl_client_certificate /etc/nginx/ssl/masterca-dod.pem; # Trusted CA
	ssl_verify_client on; # Require client certificate
	ssl_verify_depth 7;


location / {
        proxy_pass http://192.168.1.44:9090/guacamole/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	
	proxy_set_header X-SSL-CERT $ssl_client_escaped_cert;
	proxy_set_header X-SSL-Client-Serial $ssl_client_serial;
	proxy_set_header X-SSL-Client-Verify $ssl_client_verify;
	proxy_set_header X-SSL-Client-S-DN   $ssl_client_s_dn;
	proxy_set_header X-Remote-User $remote_user;
	proxy_set_header Remote-User $remote_user;
    }

location /headers {
        proxy_pass http://192.168.1.44/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	
	proxy_set_header X-SSL-CERT $ssl_client_escaped_cert;
	proxy_set_header X-SSL-Client-Serial $ssl_client_serial;
	proxy_set_header X-SSL-Client-Verify $ssl_client_verify;
	proxy_set_header X-SSL-Client-S-DN   $ssl_client_s_dn;
	proxy_set_header X-SSL-Client-I-DN   $ssl_client_i_dn;
    }
}
